using FluentInterfaceCreator.Models.Inputs;
using Newtonsoft.Json;

namespace FluentInterfaceCreator.Services;

public static class PersistenceService
{
    public const string FILE_NAME_EXTENSION = ".ficp2";

    public static List<OutputLanguage> GetOutputLanguages()
    {
        string json = File.ReadAllText("outputLanguages.json");

        return JsonConvert.DeserializeObject<List<OutputLanguage>>(json);
    }

    public static void SaveProjectToDisk(Project project, string filename)
    {
        File.WriteAllText(filename,
            JsonConvert.SerializeObject(project, Formatting.Indented));
    }

    public static Project GetProjectFromDisk(string filename)
    {
        var text = File.ReadAllText(filename);
        var project = JsonConvert.DeserializeObject<Project>(text);

        List<InterfaceSpec> autoGeneratedInterfaceSpecs =
            project.InterfaceSpecs
                .Where(i => string.IsNullOrWhiteSpace(i.Name))
                .ToList();

        foreach (var interfaceSpecToRemove in autoGeneratedInterfaceSpecs)
        {
            project.InterfaceSpecs.Remove(interfaceSpecToRemove);
        }

        return project;
    }
}